name: hyper
favicon: null
layout_spectrum: 0.70809
typography_spectrum: 0.5377519596368074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#858e99'
    - '#000000'
    - '#99c2f1'
    - '#0079ff'
  brandStrength: 0.875
  lightness: 0.2536816829815507
  saturation: 0.9977293771225959
  rhythmicContrast: 0.0775021396111697
purpose: []
