name: hyper
favicon: null
layout_spectrum: 0.50293
typography_spectrum: 0.86426
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#858e99'
    - '#000000'
    - '#99c2f1'
    - '#0079ff'
  brandStrength: 0.4375
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.0775021396111697
purpose: []
